QUBO to Ising Hamiltonian
qiskit-community/Qiskit-runtime-primitives-with-MATLAB pull request #9
Opened 2023-10-11 14:48 UTC by Bagherpoor

A class which converts Qubo matrices (Linear and Quadratic terms) to an Ising Hamiltonian along with an example were added!

2023-10-11 14:54 UTC, pacomf requested changes

2023-10-11 14:54 UTC, pacomf commented on tutorials/Enable Session/Sampler_SessionEnable.m
Remove this change :)

2023-10-11 14:54 UTC, pacomf commented on tutorials/Qubo_To_IsingHamiltonian/QUBO_Ising.m
Can we add a better structure to this file? With some extra comments about what are the things that you are doing, etc :)

2023-10-11 14:58 UTC, Bagherpoor commented on tutorials/Qubo_To_IsingHamiltonian/QUBO_Ising.m
Sure, I will add more comments to the code! I did it quickly to make sure it works! :)

2023-10-12 11:37 UTC, pacomf requested changes

2023-10-12 11:37 UTC, pacomf commented on tutorials/Qubo_To_IsingHamiltonian/QUBO_Ising.m
> +% Copyright 2023 The MathWorks, Inc.
Why this copyright here?

2023-10-12 12:13 UTC, pacomf approved these changes

2023-10-12 12:14 UTC, merged